# Site settings
# Site title
title: QuizBuzz

# Site description
description: An App to Quiz You

# Site background
background: "images/bg.jpg"

# Site logo
logo: "images/logo.png"

# Countdown clock
# (This can be commented out if not required.)
# countdown:
  # format: "2013-09-25 16:00:00 +0800"
  # launch_date: 2020-01-01
  # %d, %H, %M, %S available
  # format: "%d days, %H hours, %M minutes, %S seconds"

# Mailing list subscription
# (This can be commented out if not required.)
subscribe:
  action: "https://getquizbuzz.us18.list-manage.com/subscribe/post?u=c92341b022a1a492b034243ec&amp;id=40468781c9"
  
# Social media links
# (This can be commented out if not required.)
social:
  facebook: "getquizbuzz"
  twitter: "getquizbuzz"
  google: "102465074739119085793/102465074739119085793"
  instagram: "getquizbuzz"
#  pinterest: "#"
#  snapchat: "#"
#  linkedin: "in/#"

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - README.md
   - COPYING.txt
